<?php

namespace App\Repository\Eloquent;

use App\Models\Appointment;
use App\Repository\AppointmentRepositoryInterface;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

class AppointmentRepository extends BaseRepository implements AppointmentRepositoryInterface
{
    /**
     * @var Model
     */
    protected $model;

    /**
     * BaseRepository constructor.
     *
     * @param Model $model
     */
    public function __construct(Appointment $model)
    {
        $this->model = $model;
    }

    // Get all appointments by User ID
    public function allByUser($userId): Collection
    {
        return $this->model->where('user_id', $userId)->get(); // TODO: Change the autogenerated stub
    }
}
